# Plugin
plugin_name=
plugin_description=
plugin_version=1.0.0
plugin_author=CatsFlex
plugin_website=
plugin_id=test-plugin-id
plugin_group=me.catsflex
plugin_package=test

# Dependencies
java_version=21
minecraft_version=1.21.11
paper_api_version=R0.1-SNAPSHOT

# Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=true
org.gradle.caching=true
